jobs:
  build:
    # ...
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Linux maker prereqs
      - name: Install packaging deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm patchelf locate p7zip-full
          sudo wget -O /usr/local/bin/appimagetool \
            https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage
          sudo chmod +x /usr/local/bin/appimagetool
        # rpm/patchelf: rpm; appimage: locate + appimagetool; zip: 7z (p7zip)
        # Docs: rpm/appimage/zip makers
        # (see citations below)

      # macOS maker prereqs
      - name: Install packaging deps (macOS)
        if: runner.os == 'macOS'
        run: brew install p7zip
        # zip maker needs 7z

      - name: Install fastforge
        run: dart pub global activate fastforge

      - name: Run fastforge release
        run: fastforge release --name ${{ matrix.job_name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job_name }}-build
          # Fastforge usually outputs under dist/<version>/..., not dist/<job_name>/...
          path: dist/**/*