name: Create Cross-Platform Release

# This workflow triggers when a new tag starting with 'v' is pushed to the repository.
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release_name: linux
          - os: windows-latest
            release_name: windows
          - os: macos-latest
            release_name: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install fastforge
        run: dart pub global activate fastforge

      - name: Run fastforge release
        run: fastforge release ${{ matrix.release_name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
      
      - name: List downloaded files # for debugging
        run: ls -R dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/Linux-build/*
            dist/Windows-build/*
            dist/macOS-build/*
